controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

robotiq_gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    goal_toerance: 0.01
    allow_stalling: true
    max_effort_interface: robotiq_85_left_knuckle_joint/set_gripper_max_effort
    max_effort: 255.0
    max_velocity_interface: robotiq_85_left_knuckle_joint/set_gripper_max_velocity
    max_velocity: 255.0

robotiq_activation_controller:
  ros__parameters:
    default: true
